NumPy Intro:

To start off install and import numpy

In [2]:
import numpy as np

Next let's create our first array

In [5]:
first_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(first_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access your NumPy array the same way you would access a regular python list:

In [7]:
print(first_array[0])

[1 2 3]


Lets take a look at some basic operations we can do between Numpy arrays:

In [19]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

#Adding elements in both array to corrseponding index
print("Adding: ",first_array + second_array)

#Subtracting elements in first array from corrseponding element in second array
print("Subtracting: ",second_array - first_array)

#Multiplying elements in both array to corrseponding index
print("Multiplying: ",first_array * second_array)

#Divinding elements in first array from corrseponding element in second array
print("Divinding: ", first_array / second_array)

#Concatenating NumPy arrays
print("Concatenated Arrays: ", np.concatenate( (first_array, second_array ) ) )

Adding:  [5 7 9]
Subtracting:  [3 3 3]
Multiplying:  [ 4 10 18]
Divinding:  [0.25 0.4  0.5 ]
Concatenated Arrays:  [1 2 3 4 5 6]
