NumPy Intro:

To start off install and import numpy

In [2]:
import numpy as np

Next let's create our first array

In [5]:
first_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(first_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access your NumPy array the same way you would access a regular python list:

In [7]:
print(first_array[0])

[1 2 3]


Lets take a look at some basic operations we can do between Numpy arrays:

In [19]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

#Adding elements in both array to corrseponding index
print("Adding: ",first_array + second_array)

#Subtracting elements in first array from corrseponding element in second array
print("Subtracting: ",second_array - first_array)

#Multiplying elements in both array to corrseponding index
print("Multiplying: ",first_array * second_array)

#Divinding elements in first array from corrseponding element in second array
print("Divinding: ", first_array / second_array)

#Concatenating NumPy arrays
print("Concatenated Arrays: ", np.concatenate( (first_array, second_array ) ) )

Adding:  [5 7 9]
Subtracting:  [3 3 3]
Multiplying:  [ 4 10 18]
Divinding:  [0.25 0.4  0.5 ]
Concatenated Arrays:  [1 2 3 4 5 6]


How to use slicing operators for NumPy Arrays:
This is done in the same away as Python Lists with syntax looking like [start:end:step] with the step being optional

In [23]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array[1:4])

[2 3 4]


Notice that the start position is inclusive while the end position is not. Step was ommited in the above example

Slicing multi dimensional arrays is done in a similar manner with dimensions seperated by commas

In [27]:
my_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#[slicing for rows, slicing for columns]
print(my_array[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Lets take a look at an example where we remove every other column and row

In [30]:
my_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Orginal: \n", my_array)

Orginal 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
#passing no arguments for start and end means the array doesn't get sliced
#we provide a step of 2 for row and column which gives us every other row and column of the orginal
print("Every other column and row: \n", my_array[::2, ::2])

Every other column and row: 
 [[ 1  3  5]
 [11 13 15]]
